#!/usr/bin/env sh

# Setup.
VERSION="0.0.1"

version() {
	printf "git-jijin version %s\n" "$VERSION"

	git --version
}

# Helpers.
current_branch() {
	basename "$(git symbolic-ref HEAD)"
}

current_epoch() {
	date +%s
}

user_email() {
	git config user.email
}

new_branch() {
	echo "jijin-${1:-$(current_branch)}-$(user_email)-$(current_epoch)"
}

jijin() {
	initial_branch="$(current_branch)"

	git checkout -b "$(new_branch)"

	# cd to git root directory
	cd "$(git rev-parse --show-toplevel)"

	git add -A

	if [ -z "$1" ]; then
		message="지진이다! Branch $(current_branch)."
	else
		message="$*"
	fi

	git commit -m "$message" --no-verify

	for remote in $(git remote); do
		git push --set-upstream "${remote}" "$(current_branch)" || true
	done

	for sha in $(git rev-list -g stash); do
		git push origin "$sha":refs/heads/"$(current_branch $initial_branch)"-stash-"$sha"
	done

	printf "\n\n침착하게 계단으로 대피하세요!\n"
}

display_help() {
	cat <<-EOF

  usage:
    git jijin [options] [COMMAND] [args]

  commands:
    git jijin                        Add, commit, and push to remote in case of a jijin
    git jijin <message>              Execute git jijin with <message> for commit message


  options:
    -V, --version                   Output current version of git-jijin
    -h, --help                      Display this help information

EOF
	exit 0
}


case $1 in
	-V|--version) version; exit 0 ;;
	-h|--help) display_help; exit 0 ;;
esac

jijin "$@"
